const productData = {
  seating: [
    {
      img: "./img/product1.png",
      cate: "SOFA",
      name: "Odo ottoman",
      price: 699,
      tag: null,
      price_dis: null,
    },
    {
      img: "./img/product2.png",
      cate: "Dinning Chair",
      name: "Ready dining chair",
      price: 699.0,
      tag: ["selling", "new"],
      price_dis: null,
    },
    {
      img: "./img/product3.png",
      cate: "Dinning Chair",
      name: "Harbour side dining chair",
      price: 699.0,
      price_dis: null,
      tag: null,
    },
    {
      img: "./img/product4.png",
      cate: "SOFA",
      name: "Tearoom club chair",
      price: 699.0,
      price_dis: 500,
      tag: ["sale"],
      discout: 30,
    },
    {
      img: "./img/product5.png",
      cate: "Dinning Chair",
      name: "Co dining chair",
      price: 699.0,
      tag: null,
      price_dis: null,
    },
    {
      img: "./img/product6.png",
      cate: "SOFA",
      name: "Knitting lounge chair",
      price: 699.0,
      tag: null,
      price_dis: null,
    },
  ],
  table: [
    {
      img: "./img/product7.png",
      cate: "Wood Table",
      name: "Odo Table",
      price: 699.0,
      tag: null,
      price_dis: null,
    },
    {
      img: "./img/product8.png",
      cate: "Wood Table",
      name: "Wood Table Good",
      price: 699.0,
      tag: null,
      price_dis: null,
    },
    {
      img: "./img/product9.png",
      cate: "Dinning Table",
      name: "Harbour side dining Table",
      price: 699.0,
      tag: null,
      price_dis: null,
    },
    {
      img: "./img/product10.png",
      cate: "SOFA",
      name: "Tearoom club chair",
      price: 699.0,
      tag: null,
      price_dis: null,
    },
    {
      img: "./img/product11.png",
      cate: "Dinning Chair",
      name: "Co dining chair",
      price: 699.0,
      tag: null,
      price_dis: null,
    },
    {
      img: "./img/product12.png",
      cate: "SOFA",
      name: "Knitting lounge chair",
      price: 699.0,
      tag: null,
      price_dis: null,
    },
  ],
  storage: [
    {
      img: "./img/product12.png",
      cate: "SOFA storage",
      name: "Odo ottoman",
      price: 699.0,
      tag: null,
      price_dis: null,
    },
    {
      img: "./img/product11.png",
      cate: "Dinning Chair",
      name: "Ready dining chair",
      price: 699.0,
      tag: null,
      price_dis: null,
    },
    {
      img: "./img/product10.png",
      cate: "Dinning Chair",
      name: "Harbour side dining chair",
      price: 699.0,
      tag: null,
      price_dis: null,
    },
    {
      img: "./img/product4.png",
      cate: "SOFA",
      name: "Tearoom club chair",
      price: 699.0,
      tag: null,
      price_dis: null,
    },
    {
      img: "./img/product5.png",
      cate: "Dinning Chair",
      name: "Co dining chair",
      price: 699.0,
      tag: null,
      price_dis: null,
    },
    {
      img: "./img/product6.png",
      cate: "SOFA",
      name: "Knitting lounge chair",
      price: 699.0,
      tag: null,
      price_dis: null,
    },
  ],
  lighting: [
    {
      img: "./img/product7.png",
      cate: "SOFA lighting",
      name: "Odo ottoman",
      price: 699.0,
      tag: null,
      price_dis: null,
    },
    {
      img: "./img/product11.png",
      cate: "Dinning Chair",
      name: "Ready dining chair",
      price: 699.0,
      tag: null,
      price_dis: null,
    },
    {
      img: "./img/product8.png",
      cate: "Dinning Chair",
      name: "Harbour side dining chair",
      price: 699.0,
      tag: null,
      price_dis: null,
    },
    {
      img: "./img/product4.png",
      cate: "SOFA",
      name: "Tearoom club chair",
      price: 699.0,
      tag: null,
      price_dis: null,
    },
    {
      img: "./img/product5.png",
      cate: "Dinning Chair",
      name: "Co dining chair",
      price: 699.0,
      tag: null,
      price_dis: null,
    },
    {
      img: "./img/product6.png",
      cate: "SOFA",
      name: "Knitting lounge chair",
      price: 699.0,
      tag: null,
      price_dis: null,
    },
  ],
  decor: [
    {
      img: "./img/product12.png",
      cate: "SOFA decor",
      name: "Odo ottoman",
      price: 699.0,
      tag: null,
      price_dis: null,
    },
    {
      img: "./img/product2.png",
      cate: "Dinning Chair",
      name: "Ready dining chair",
      price: 699.0,
      tag: null,
      price_dis: null,
    },
    {
      img: "./img/product8.png",
      cate: "Dinning Chair",
      name: "Harbour side dining chair",
      price: 699.0,
      tag: null,
      price_dis: null,
    },
    {
      img: "./img/product4.png",
      cate: "SOFA",
      name: "Tearoom club chair",
      price: 699.0,
      tag: null,
      price_dis: null,
    },
    {
      img: "./img/product5.png",
      cate: "Dinning Chair",
      name: "Co dining chair",
      price: 699.0,
      tag: null,
      price_dis: null,
    },
    {
      img: "./img/product6.png",
      cate: "SOFA",
      name: "Knitting lounge chair",
      price: 699.0,
      tag: null,
      price_dis: null,
    },
  ],
};
export default productData;
